services:
  db:
    image: cookbook.azurecr.io/postgres:latest
    build: db
    environment:
      POSTGRES_DB: cookbook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  app:
    image: cookbook.azurecr.io/springboot-app:latest
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cookbook_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password123
      APP_FRONTEND_URL: http://localhost
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-}
    ports:
      - "8080:8080"
    depends_on:
      - db

  ui:
    image: cookbook.azurecr.io/cookbook-ui:latest
    build: ./cookbook-frontend
    ports:
      - "80:80"
    depends_on:
      - app